/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "secondary": "#a83900",
        "error": "#ba1a1a",
        "surface-dim": "#dcd9d9",
        "secondary-fixed-dim": "#ffb59a",
        "secondary-container": "#fc6018",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-container": "#531800",
        "surface-container-high": "#eae7e7",
        "on-tertiary-fixed": "#001c3a",
        "tertiary-fixed-dim": "#a5c8ff",
        "on-secondary-fixed-variant": "#802a00",
        "surface-container": "#f0eded",
        "on-secondary-fixed": "#380d00",
        "on-tertiary-fixed-variant": "#004786",
        "primary": "#00450d",
        "on-tertiary": "#ffffff",
        "primary-container": "#1b5e20",
        "on-primary-container": "#90d689",
        "tertiary": "#003b71",
        "background": "#fcf9f8",
        "on-primary-fixed": "#002203",
        "on-primary-fixed-variant": "#0c5216",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#a3c7ff",
        "surface-bright": "#fcf9f8",
        "primary-fixed-dim": "#91d78a",
        "outline": "#717a6d",
        "on-error": "#ffffff",
        "tertiary-container": "#005299",
        "on-surface-variant": "#41493e",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#acf4a4",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#d4e3ff",
        "surface-container-low": "#f6f3f2",
        "surface-tint": "#2a6b2c",
        "surface-container-highest": "#e5e2e1",
        "inverse-surface": "#303030",
        "on-background": "#1b1c1c",
        "secondary-fixed": "#ffdbcf",
        "outline-variant": "#c0c9bb",
        "inverse-primary": "#91d78a",
        "surface": "#fcf9f8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin": "1rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["16px", { "lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "fontWeight": "600" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-sm": ["16px", { "lineHeight": "22px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "26px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
