const TermsPage = () => {
  return (
    <div className="mx-auto max-w-4xl px-4 text-slate-200">
      <div className="rounded-2xl border border-slate-800 bg-slate-900/80 p-6 sm:p-8">
        <p className="mb-3 text-xs font-medium uppercase tracking-[0.18em] text-slate-400">Terms and Conditions</p>
        <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">Platform terms</h1>

        <div className="mt-8 space-y-6 text-sm leading-7 text-slate-300">
          <p>
            These terms govern access to and use of the agricultural platform and any associated services. By registering,
            logging in, or using the application, you agree to comply with these terms and all applicable laws.
          </p>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">Account use</h2>
            <p>
              You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs
              under your account. You must provide accurate information and use the platform only for lawful agricultural,
              operational, and compliance-related purposes.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">Operational data</h2>
            <p>
              Users may upload operational data, field records, crop information, compliance documents, and other content for
              analysis and reporting. You retain ownership of your content, but you grant the platform the right to process
              it as needed to provide requested services and maintain system features.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">Service availability</h2>
            <p>
              The platform may be updated, maintained, or temporarily unavailable for scheduled or unscheduled service work.
              We do not guarantee continuous uptime or absolute accuracy of recommendations generated by analytical tools.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">Intellectual property</h2>
            <p>
              The platform design, branding, user interface, documentation, and system workflows are proprietary to the
              operator of this service unless otherwise stated. User-submitted data remains subject to the ownership rights
              described in the account agreement and applicable law.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">Limitation of liability</h2>
            <p>
              The platform is provided on an “as is” basis. We do not guarantee that recommendations, forecasts, or
              operational insights will be error-free or appropriate for every farming context. Any operational decisions
              based on platform output remain the responsibility of the user or organization.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">Governing law</h2>
            <p>
              These terms are governed by the laws of the jurisdiction in which the platform is deployed. Disputes related
              to the service should be addressed through the applicable legal channels for that jurisdiction.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;

