"""create disease_reports weed_reports pest_risk_scores livestock livestock_health_reports tables

Revision ID: 1535432790c1
Revises: 4bd5c72d8d75
Create Date: 2026-09-12 16:06:44.923850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1535432790c1'
down_revision: Union[str, Sequence[str], None] = '4bd5c72d8d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pest_risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('village_name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('contributing_reports_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pest_risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pest_risk_scores_district'), ['district'], unique=False)

    op.create_table('disease_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('predicted_disease', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='disease_severity'), nullable=False),
    sa.Column('treatment_recommendation', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_public_surveillance', sa.Boolean(), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disease_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_reports_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_reports_farm_id'), ['farm_id'], unique=False)

    op.create_table('livestock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('animal_type', sa.Enum('cow', 'buffalo', 'goat', 'poultry', name='animal_type'), nullable=False),
    sa.Column('tag_id', sa.String(length=100), nullable=False),
    sa.Column('vaccination_schedule', sa.JSON(), nullable=False),
    sa.Column('breeding_cycle', sa.JSON(), nullable=False),
    sa.Column('milk_yield_log', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_livestock_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_livestock_tag_id'), ['tag_id'], unique=False)

    op.create_table('weed_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('predicted_species', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommended_herbicide', sa.String(length=255), nullable=False),
    sa.Column('dosage_ml_per_acre', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weed_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weed_reports_farm_id'), ['farm_id'], unique=False)

    op.create_table('livestock_health_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('livestock_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('predicted_condition', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('vet_booking_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('livestock_health_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_livestock_health_reports_livestock_id'), ['livestock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock_health_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_livestock_health_reports_livestock_id'))

    op.drop_table('livestock_health_reports')
    with op.batch_alter_table('weed_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weed_reports_farm_id'))

    op.drop_table('weed_reports')
    with op.batch_alter_table('livestock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_livestock_tag_id'))
        batch_op.drop_index(batch_op.f('ix_livestock_farm_id'))

    op.drop_table('livestock')
    with op.batch_alter_table('disease_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disease_reports_farm_id'))
        batch_op.drop_index(batch_op.f('ix_disease_reports_district'))

    op.drop_table('disease_reports')
    with op.batch_alter_table('pest_risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pest_risk_scores_district'))

    op.drop_table('pest_risk_scores')
    # ### end Alembic commands ###
