"""create crop_plans rotation_plans variety_recommendations prescription_maps tables

Revision ID: 4bd5c72d8d75
Revises: 6088d5eb1a27
Create Date: 2026-09-12 15:55:45.798639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd5c72d8d75'
down_revision: Union[str, Sequence[str], None] = '6088d5eb1a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.Enum('kharif', 'rabi', 'zaid', name='season_enum'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('recommended_crop', sa.String(length=255), nullable=False),
    sa.Column('recommended_variety', sa.String(length=255), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('expected_investment', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'harvested', name='plan_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_plans_farm_id'), ['farm_id'], unique=False)

    op.create_table('prescription_maps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('zone_prescriptions', sa.JSON(), nullable=False),
    sa.Column('export_format', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_maps_farm_id'), ['farm_id'], unique=False)

    op.create_table('rotation_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('season_sequence', sa.JSON(), nullable=False),
    sa.Column('rl_confidence', sa.Float(), nullable=False),
    sa.Column('soil_impact_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rotation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotation_plans_farm_id'), ['farm_id'], unique=False)

    op.create_table('variety_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('recommended_varieties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variety_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variety_recommendations_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variety_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variety_recommendations_farm_id'))

    op.drop_table('variety_recommendations')
    with op.batch_alter_table('rotation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotation_plans_farm_id'))

    op.drop_table('rotation_plans')
    with op.batch_alter_table('prescription_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_maps_farm_id'))

    op.drop_table('prescription_maps')
    with op.batch_alter_table('crop_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_plans_farm_id'))

    op.drop_table('crop_plans')
    # ### end Alembic commands ###
