"""create water_soil and vision_forecast tables

Revision ID: 6407017bcef9
Revises: 1535432790c1
Create Date: 2026-09-12 16:18:39.464826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6407017bcef9'
down_revision: Union[str, Sequence[str], None] = '1535432790c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=False),
    sa.Column('low_ci', sa.Float(), nullable=False),
    sa.Column('high_ci', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_forecasts_district'), ['district'], unique=False)

    op.create_table('climate_risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('drought_risk', sa.Float(), nullable=False),
    sa.Column('flood_risk', sa.Float(), nullable=False),
    sa.Column('heat_risk', sa.Float(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('climate_risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_climate_risk_scores_farm_id'), ['farm_id'], unique=False)

    op.create_table('grain_quality_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('moisture_pct', sa.Float(), nullable=False),
    sa.Column('broken_pct', sa.Float(), nullable=False),
    sa.Column('foreign_matter_pct', sa.Float(), nullable=False),
    sa.Column('grade', sa.Enum('A', 'B', 'C', name='grain_grade'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grain_quality_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grain_quality_reports_farm_id'), ['farm_id'], unique=False)

    op.create_table('irrigation_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recommended_liters', sa.Float(), nullable=False),
    sa.Column('current_moisture_pct', sa.Float(), nullable=False),
    sa.Column('et0_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('irrigation_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_irrigation_schedules_farm_id'), ['farm_id'], unique=False)

    op.create_table('plant_counts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('gaps_detected', sa.Integer(), nullable=False),
    sa.Column('growth_stage', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_counts_farm_id'), ['farm_id'], unique=False)

    op.create_table('soil_health_maps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('grid_data', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soil_health_maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soil_health_maps_farm_id'), ['farm_id'], unique=False)

    op.create_table('stress_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ndvi_value', sa.Float(), nullable=False),
    sa.Column('ndwi_value', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Enum('none', 'mild', 'moderate', 'severe', name='stress_level'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stress_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stress_alerts_farm_id'), ['farm_id'], unique=False)

    op.create_table('yield_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('low_kg', sa.Float(), nullable=False),
    sa.Column('median_kg', sa.Float(), nullable=False),
    sa.Column('high_kg', sa.Float(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yield_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yield_forecasts_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yield_forecasts_farm_id'))

    op.drop_table('yield_forecasts')
    with op.batch_alter_table('stress_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_alerts_farm_id'))

    op.drop_table('stress_alerts')
    with op.batch_alter_table('soil_health_maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soil_health_maps_farm_id'))

    op.drop_table('soil_health_maps')
    with op.batch_alter_table('plant_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_counts_farm_id'))

    op.drop_table('plant_counts')
    with op.batch_alter_table('irrigation_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_irrigation_schedules_farm_id'))

    op.drop_table('irrigation_schedules')
    with op.batch_alter_table('grain_quality_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grain_quality_reports_farm_id'))

    op.drop_table('grain_quality_reports')
    with op.batch_alter_table('climate_risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_climate_risk_scores_farm_id'))

    op.drop_table('climate_risk_scores')
    with op.batch_alter_table('price_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_forecasts_district'))

    op.drop_table('price_forecasts')
    # ### end Alembic commands ###
