"""create advanced_ai tables

Revision ID: 659d79810cec
Revises: 71c57daec0d6
Create Date: 2026-09-13 11:55:58.146303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659d79810cec'
down_revision: Union[str, Sequence[str], None] = '71c57daec0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fl_training_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('participating_farms', sa.JSON(), nullable=False),
    sa.Column('aggregate_accuracy', sa.Float(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('causal_simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('current_decision', sa.JSON(), nullable=False),
    sa.Column('proposed_change', sa.JSON(), nullable=False),
    sa.Column('projected_delta', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('causal_simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_causal_simulations_farm_id'), ['farm_id'], unique=False)

    op.create_table('multimodal_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('combined_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('multimodal_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_multimodal_queries_farm_id'), ['farm_id'], unique=False)

    op.create_table('voice_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('transcribed_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_queries_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_queries_farm_id'))

    op.drop_table('voice_queries')
    with op.batch_alter_table('multimodal_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_multimodal_queries_farm_id'))

    op.drop_table('multimodal_queries')
    with op.batch_alter_table('causal_simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_causal_simulations_farm_id'))

    op.drop_table('causal_simulations')
    op.drop_table('fl_training_runs')
    # ### end Alembic commands ###
