"""create gov_compliance and community tables

Revision ID: 71c57daec0d6
Revises: d9fcf803d7a5
Create Date: 2026-09-13 11:46:10.146248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c57daec0d6'
down_revision: Union[str, Sequence[str], None] = 'd9fcf803d7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fpo_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('member_farm_ids', sa.JSON(), nullable=False),
    sa.Column('pooled_purchases', sa.JSON(), nullable=False),
    sa.Column('pooled_sales', sa.JSON(), nullable=False),
    sa.Column('scheme_compliance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('benefit_amount', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('level', sa.Enum('central', 'state', name='scheme_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schemes_name'), ['name'], unique=True)

    op.create_table('shg_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('member_farm_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('weather', 'irrigation', 'pest', 'spray_window', name='alert_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_farm_id'), ['farm_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Enum('aadhaar', 'land_record', 'bank_passbook', 'insurance', name='doc_type'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('ocr_extracted', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_farm_id'), ['farm_id'], unique=False)

    op.create_table('eligibility_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eligibility_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eligibility_matches_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eligibility_matches_scheme_id'), ['scheme_id'], unique=False)

    op.create_table('grower_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('district_percentile', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grower_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grower_scores_farm_id'), ['farm_id'], unique=False)

    op.create_table('season_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('investment', sa.Float(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('roi_pct', sa.Float(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('season_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_season_reports_farm_id'), ['farm_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='ticket_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_farm_id'), ['farm_id'], unique=False)

    op.create_table('shg_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shg_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_booking_id', sa.Uuid(), nullable=False),
    sa.Column('split_amounts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_booking_id'], ['equipment_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shg_id'], ['shg_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shg_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shg_bookings_equipment_booking_id'), ['equipment_booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shg_bookings_shg_id'), ['shg_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shg_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shg_bookings_shg_id'))
        batch_op.drop_index(batch_op.f('ix_shg_bookings_equipment_booking_id'))

    op.drop_table('shg_bookings')
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_tickets_farm_id'))

    op.drop_table('support_tickets')
    with op.batch_alter_table('season_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_season_reports_farm_id'))

    op.drop_table('season_reports')
    with op.batch_alter_table('grower_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grower_scores_farm_id'))

    op.drop_table('grower_scores')
    with op.batch_alter_table('eligibility_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eligibility_matches_scheme_id'))
        batch_op.drop_index(batch_op.f('ix_eligibility_matches_farm_id'))

    op.drop_table('eligibility_matches')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_farm_id'))

    op.drop_table('documents')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_farm_id'))

    op.drop_table('alerts')
    op.drop_table('shg_groups')
    with op.batch_alter_table('schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schemes_name'))

    op.drop_table('schemes')
    op.drop_table('fpo_groups')
    # ### end Alembic commands ###
