"""create marketplace and finance tables

Revision ID: d9fcf803d7a5
Revises: 6407017bcef9
Create Date: 2026-09-13 11:38:21.763642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fcf803d7a5'
down_revision: Union[str, Sequence[str], None] = '6407017bcef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_standing_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.String(length=255), nullable=False),
    sa.Column('buyer_type', sa.Enum('retail', 'horeca', 'processor', name='buyer_type'), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('recurring_qty_kg', sa.Float(), nullable=False),
    sa.Column('fulfilment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.String(length=255), nullable=False),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('qty_needed_kg', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=False),
    sa.Column('price_offered', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gang_id', sa.String(length=255), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=False),
    sa.Column('daily_wage', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('availability_calendar', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('seed', 'fertilizer', 'pesticide', name='product_category'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('vendor_id', sa.String(length=255), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('buyer_requirement_id', sa.Uuid(), nullable=False),
    sa.Column('farm_ids', sa.JSON(), nullable=False),
    sa.Column('aggregated_qty_kg', sa.Float(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_requirement_id'], ['buyer_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exchange_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_matches_buyer_requirement_id'), ['buyer_requirement_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('marketplace', 'rental', 'scheme_dbt', 'exchange_sale', 'loan_disbursement', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'escrow_held', 'released', 'refunded', name='transaction_status'), nullable=False),
    sa.Column('related_entity_id', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('equipment_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_route_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['equipment_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_bookings_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_bookings_listing_id'), ['listing_id'], unique=False)

    op.create_table('fraud_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fraud_flags_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('insurance_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.String(length=255), nullable=False),
    sa.Column('loss_event_date', sa.Date(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('filed', 'under_review', 'approved', 'settled', name='claim_status'), nullable=False),
    sa.Column('settlement_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_claims_farm_id'), ['farm_id'], unique=False)

    op.create_table('labor_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['labor_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_bookings_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labor_bookings_listing_id'), ['listing_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'approved', 'disbursed', 'repaid', name='loan_status'), nullable=False),
    sa.Column('lender', sa.String(length=255), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=True),
    sa.Column('terms', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_farm_id'), ['farm_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('placed', 'shipped', 'delivered', 'delayed', name='order_status'), nullable=False),
    sa.Column('delivery_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('critical_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_product_id'), ['product_id'], unique=False)

    op.create_table('warehouse_bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.String(length=255), nullable=False),
    sa.Column('qty_kg', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=False),
    sa.Column('e_nwr_id', sa.String(length=255), nullable=True),
    sa.Column('loan_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_bookings_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_bookings_farm_id'))

    op.drop_table('warehouse_bookings')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_product_id'))
        batch_op.drop_index(batch_op.f('ix_orders_farm_id'))

    op.drop_table('orders')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_farm_id'))

    op.drop_table('loans')
    with op.batch_alter_table('labor_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_bookings_listing_id'))
        batch_op.drop_index(batch_op.f('ix_labor_bookings_farm_id'))

    op.drop_table('labor_bookings')
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_farm_id'))

    op.drop_table('insurance_claims')
    with op.batch_alter_table('fraud_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_flags_transaction_id'))

    op.drop_table('fraud_flags')
    with op.batch_alter_table('equipment_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_bookings_listing_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_bookings_farm_id'))

    op.drop_table('equipment_bookings')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('exchange_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_matches_buyer_requirement_id'))

    op.drop_table('exchange_matches')
    op.drop_table('products')
    op.drop_table('labor_listings')
    op.drop_table('equipment_listings')
    op.drop_table('buyer_requirements')
    op.drop_table('b2b_standing_orders')
    # ### end Alembic commands ###
